services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=demo_jwt
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'

  backend:
    build:
      context: ../jwt-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.23.3
    ports:
      - 3000:80
    volumes:
      - ../jwt-frontend/build:/usr/share/nginx/html

# docker compose -p jwt-fullstack up -d
# npx sequelize-cli db:migrate